### ISSUE TITLE
Spaces in the text attribute throw

### ISSUE THREAD

**Issue by steveoh** [agrc/masquerade#124]
postgres thinks this is a string search and the quote is unterminated. I wonder if all quotes should be stripped. Double quotes would be considered a column etc so I don't think anything good will come from it. 

e.g. `/suggest?f=json&text=3000 N MAIN ST, LOGAN'&maxSuggestions=6`

**Comment by stdavis** [comment]
What about for geocoding? Should I strip them for requests going to the web API as well?

**Comment by steveoh** [comment]
there are 0 roads and 453 address points with a single quote. I think you could strip it
