### ISSUE TITLE
Migrate Test App from WAB to an Instant app

### ISSUE THREAD

**Issue by stdavis** [agrc/masquerade#183]
[This app](https://utah.maps.arcgis.com/apps/webappviewer/index.html?id=97a1529c31c84a93956968d48c6e08ad) ([referenced in README.md](https://github.com/agrc/masquerade/blob/17c4bd07b578abb00919a91184085fe1d7a8414c/README.md#L140)) is quite useful for testing the different environments. It needs to be migrated to EB or some other supported configurable app.

**Comment by nathankota** [comment]
> It needs to be migrated to EB or some other supported configurable app.
I think another Instant app would be fine, just not the Minimalist template
