### ISSUE TITLE
API Key/Account Number requirement

### ISSUE THREAD

**Issue by stdavis** [agrc/masquerade#25]
How important is it to track usage for this service? Do we need to add an API key or account number similar to print proxy to the URL?

**Comment by stdavis** [comment]
@nathankota will ask @brigsz about this.

**Comment by nathankota** [comment]
@stdavis please confirm that _without_ the API key implementation, we could still obtain analytics about the number of searches completed by masquerade...correct?

**Comment by stdavis** [comment]
Yes, that's correct. We can still collect analytics on masquerade requests, we just can't separate them by the requester/user.

**Comment by nathankota** [comment]
confirmed by @brigsz that we are okay to proceed without an API key or account number
