### ISSUE TITLE
Estimate GCP costs

### ISSUE THREAD

**Issue by stdavis** [agrc/masquerade#34]
Matt is wondering...

![image](https://user-images.githubusercontent.com/1326248/149238417-6258d6e2-a057-460d-97c1-0895d23ac857.png)

@steveoh Does this look like a legit estimate to you?

**Comment by steveoh** [comment]
I'd say it's a good spot to start and see what happens in the real world.

**Comment by stdavis** [comment]
@brigsz The estimate for masquerade accepting 2,000,000 requests is $8.21 per month. So nothing to worry about from what I can see.
