### ISSUE TITLE
Security Forms (A&A)

### ISSUE THREAD

**Issue by stdavis** [agrc/masquerade#39]
At least create the diagrams.

**Comment by steveoh** [comment]
I believe this has been completed. Please verify.

**Comment by stdavis** [comment]
I don't see it in Lucid or Archer. Do we need it? If so, I'll work up some diagrams.

**Comment by stdavis** [comment]
I've got an appointment with Ryan B to take care of this tomorrow.

**Comment by stdavis** [comment]
Archer package was submitted for approval today.

**Comment by stdavis** [comment]
I dinged Ryan Bramwell again today to ask for an update.

**Comment by stdavis** [comment]
Ryan submitted it last month and Phil still hasn't done anything on it. He's going to ding him again.

**Comment by stdavis** [comment]
/remind me to check back in with Ryan in two weeks

**Comment by stdavis** [comment]
Ryan told me that security has been ignoring his A&A approval requests for the past month. 🤯

I asked Matt to grease the wheels.

**Comment by stdavis** [comment]
Annnnnnnd, it's now been approved by security. @brigsz has a special talent for lighting fires. Thanks!
